### ISSUE TITLE
Attempting to check the status JBoss service even if it's not installed

### ISSUE THREAD

**Issue by itlackey** [PCFDev/i2b2-Windows-Installer#4]
i2b2 Data Installation Completed
Get-Service : Cannot find any service with service name 'jboss'.
At C:\Tools\i2b2-Windows-Installer-master\install.ps1:118 char:5
- if((Get-Service jboss).Status -eq "Stopped") {
-     ~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (jboss:String) [Get-Service], ServiceCommandException
  - FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand

**Comment by Hahn886** [comment]
Added additional check for service installed. Issue resolved.
